
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpwpxgvuztobujadrgty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wd3B4Z3Z1enRvYnVqYWRyZ3R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzYzOTcsImV4cCI6MjA2MDgxMjM5N30.wTmkxPjrnKDkFMDZ9s1o4uU_VgiAlExP0ySAYkp13qA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      fetch: (...args) => {
        const [url, options] = args;
        console.log(`Supabase Fetch: ${options?.method || 'GET'} ${url}`);
        return fetch(...args);
      }
    }
  }
);

// Add debug logging for API calls
supabase.auth.onAuthStateChange((event, session) => {
  console.log('Supabase Auth Event:', event, session?.user?.id || 'No user');
});
